-- Crear base de datos si no existe y usarla
CREATE DATABASE IF NOT EXISTS `bd_productos_sanetta`;
USE `bd_productos_sanetta`;

-- Establecer configuraciones
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";

-- Crear tabla de ingredientes
CREATE TABLE `tbl_ingredientes` (
  `id_ingrediente` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_ingrediente`)
);

-- Insertar datos en tabla de ingredientes
INSERT INTO `tbl_ingredientes` (`id_ingrediente`, `nombre`) VALUES
(1, 'Agua del grifo'),
(2, 'Leche de soja'),
(3, 'Gelcremfred'),
(4, 'Cobertura negra 70%'),
(5, 'Sal'),
(6, 'Aceite girasol'),
(7, 'Cremoso de Chocolate'),
(8, 'Cobertura negra 55%'),
(9, 'Azúcar blanco'),
(10, 'Glucosa'),
(11, 'Cacao en polvo'),
(12, 'Pectina NH'),
(13, 'Baño de chocolate'),
(14, 'Harina de trigo floja'),
(15, 'Levadura química'),
(16, 'Proteina patata'),
(17, 'Azúcar moreno'),
(18, 'Nata'),
(19, 'Queso tofutti'),
(20, 'Disco 24 cm'),
(21, 'Caja 26 cm'),
(22, 'Margarina'),
(23, 'Coco rallado'),
(24, 'Remolacha cocida'),
(25, 'Glass'),
(26, 'Anacardos crudos'),
(27, 'Aceite de coco'),
(28, 'Colorante rojo en polvo'),
(29, 'Levadura fresca'),
(30, 'Harina media fuerza'),
(31, 'Canela molida'),
(32, 'Gotas chocolate'),
(33, 'Avellanas'),
(34, 'Banana'),
(35, 'Mix sin gluten'),
(36, 'Panela'),
(37, 'Nueces'),
(38, 'Manzana'),
(39, 'Cebolla morada'),
(40, 'Zumo limón'),
(41, 'Pasas'),
(42, 'Maizena'),
(43, 'Almidón tapioca'),
(44, 'Trigo sarraceno ECO'),
(45, 'Fécula patata'),
(46, 'Harina de arroz'),
(47, 'Corteza limón troceada'),
(48, 'Corteza naranja troceada'),
(49, 'Gelcremcalent'),
(50, 'Leche coco en polvo'),
(51, 'Pasta almendra cruda'),
(52, 'Puré pasión'),
(53, 'Inulina'),
(54, 'Vainilla pasta'),
(55, 'Lecitina de soja'),
(56, 'Vegan mousse'),
(57, 'Naturemul'),
(58, 'Agar-agar'),
(59, 'Pure frutos rojos'),
(60, 'Frambuesa congelada'),
(61, 'Xantana'),
(62, 'Vinagre de manzana'),
(63, 'Harina de almendra'),
(64, 'Bicarbonato'),
(65, 'Manteca de cacao'),
(66, 'Amaretto'),
(67, 'Frutos rojos congelados'),
(68, 'Jengibre en polvo'),
(69, 'Nuez moscada en grano'),
(70, 'Puré frambuesa'),
(71, 'Colorante rojo en pasta'),
(72, 'Copos de avena sin gluten'),
(73, 'Almendra en bastoncitos'),
(74, 'Sojawhip'),
(75, 'Yogur soja'),
(76, 'Pistacho pelado'),
(77, 'Queso mozarella rallada'),
(78, 'Pimienta negra'),
(79, 'Orégano seco'),
(80, 'Pimentón picante'),
(81, 'Pimentón dulce'),
(82, 'Ajo en polvo'),
(83, 'Cúrcuma en polvo'),
(84, 'Cajita individual roll'),
(85, 'Nutela'),
(86, 'Leche coco en la lata'),
(87, 'Dulce de leche'),
(88, 'Crema de limón'),
(89, 'Merengue italiano'),
(90, 'Bizcocho cacao grande (p)'),
(91, 'Caja 23 cm'),
(92, 'Disco 21 cm'),
(93, 'Roll canela (p)'),
(94, 'Discos 30 cm'),
(95, 'Caja 32 cm'),
(96, 'Bizcocho tiramisu'),
(97, 'Salsa f.r. tiramisu'),
(98, 'Spray terciopelo rojo'),
(99, 'Crema tiramisu'),
(100, 'Cartoncito 8 cm'),
(101, 'Café expreso'),
(102, 'Café tiramisú'),
(103, 'Zanahoria'),
(104, 'Bizcocho carrot grande (p)'),
(105, 'Bizcocho cacao grande sg (p)'),
(106, 'Bizcocho carrot grande sg (p)'),
(107, 'Mermelada frambuesa'),
(108, 'Bizcocho pink velvet grande'),
(109, 'Bizcocho pink velvet grande sg'),
(110, 'Cookies doble chocolate'),
(111, 'Pasta brisa sin azúcar'),
(112, 'Almidón patata'),
(113, 'Dátiles pasta'),
(114, 'Crumble'),
(115, 'Glass antihumedad'),
(116, 'Pasta sable de almendra'),
(117, 'Soplete'),
(118, 'Chocolate blanco casero'),
(119, 'Praline avellana'),
(120, 'Plancha cacao sg'),
(121, 'Mousse chocolate 70%'),
(122, 'Mermelada frutos rojos'),
(123, 'Frutos rojos frescos'),
(124, 'Gel frío'),
(125, 'Manzana roll'),
(126, 'Carton base 20cm'),
(127, 'Carton base 22 cm'),
(128, 'Vasito compostable'),
(129, 'Ganache macaron choco sg (p)'),
(130, 'Base macaron sg (p)'),
(131, 'Flor de sal'),
(132, 'Harina trigo integral'),
(133, 'Aceite de oliva'),
(134, 'Masa quiche'),
(135, 'Levadura nutricional'),
(136, 'Cebolla blanca'),
(137, 'Papelinas nº8'),
(138, 'Tomate frito'),
(139, 'Aceituna negra'),
(140, 'Cajas catering marron'),
(141, 'Cajas catering blanca'),
(142, 'Papel de horno'),
(143, 'Tomate seco'),
(144, 'Pimiento rojo'),
(145, 'Pimiento verde'),
(146, 'Caja plumcake'),
(147, 'Base rectangular'),
(148, 'Cebolla caramelizada'),
(149, 'Griottines'),
(150, 'Comino en polvo'),
(151, 'Sobrasada'),
(152, 'Ralladura limón'),
(153, 'Crema de almendras'),
(154, 'Nueces pecanas'),
(155, 'Bizcocho german cake (p)'),
(156, 'Crema german cake (p)'),
(157, 'Caja alta de 15 cm alto grande'),
(158, 'Bizcocho almendra sin gluten (p)'),
(159, 'Margarina casera'),
(160, 'Sirope de Agave'),
(161, 'Goma garrofín'),
(162, 'Ganache opera'),
(163, 'Glaseado opera'),
(164, 'Crema cafe opera'),
(165, 'Polvo dorado'),
(166, 'Cebolla cortada congelada'),
(167, 'Cacahuetes'),
(168, 'Calabaza'),
(169, 'Mermelada calabaza'),
(170, 'Brisa de cacao'),
(171, 'Anis del mono'),
(172, 'Pistachos'),
(173, 'Pasta pura pistacho'),
(174, 'Mazapan'),
(175, 'Pipas calabaza'),
(176, 'Eko'),
(177, 'Piñon castellano'),
(178, 'Colorante negro'),
(179, 'Garrapiñadas de calabaza'),
(180, 'Ganache pistacho'),
(181, 'Praline avellana bon llevat'),
(182, 'Harina de trigo fuerza'),
(183, 'Harina de garbanzo'),
(184, 'Cabello de angel'),
(185, 'Café Soluble Classic'),
(186, 'Chocolate blanco'),
(187, 'Naranja fresca'),
(188, 'Baño almendra tronco vainilla'),
(189, 'Crumble almendra'),
(190, 'Bizcocho naranja sin gluten'),
(191, 'Confitura maracuya'),
(192, 'Mousse vainilla'),
(193, 'Frambuesa fresca'),
(194, 'Agua de azahar'),
(195, 'Roscones reyes'),
(196, 'Cajas roscon 26x26'),
(197, 'Cajas troncos'),
(198, 'Habas reyes'),
(199, 'Rey porcelana'),
(200, 'Corona reyes prince'),
(201, 'Crema pastelera'),
(202, 'Albahaca fresca'),
(203, 'Cebolla blanca grande'),
(204, 'Arandanos congelados'),
(205, 'Eritritol'),
(206, 'Sésamo tostado'),
(207, 'Anis en grano'),
(208, 'Cajitas san valentin'),
(209, 'Pipas girasol'),
(210, 'Piña fresca'),
(211, 'Menta fresca'),
(212, 'Maracuyá fresco'),
(213, 'Mermelada maracuyá'),
(214, 'Mango fresco'),
(215, 'Capsulas metal trufa'),
(216, 'Brownie (p)'),
(217, 'Masa quiche'),
(218, 'Champiñones'),
(219, 'Calabacin'),
(220, 'Espinacas'),
(221, 'Puerro'),
(222, 'Mousse genércia'),
(223, 'Bizcocho calabacin grande sin gluten'),
(224, 'Peras'),
(225, 'Romero'),
(226, 'Physalis'),
(227, 'Cookies doble chocolate sin gluten'),
(228, 'Cebollino'),
(229, 'Patata'),
(230, 'Pmiento rojo'),
(231, 'Berenjena'),
(232, 'Alcaparras'),
(233, 'Soja texturizada'),
(234, 'Vino blanco'),
(235, 'Chorizo heura'),
(236, 'Farça chorizo, patata y queso'),
(237, 'Farça verduritas con soja text.'),
(238, 'Farça champiñon'),
(239, 'Pollo heura'),
(240, 'Salsa pesto');

-- Crear tabla de tamaños
CREATE TABLE `tbl_tamanos` (
  `id_tamano` INT(11) NOT NULL AUTO_INCREMENT,
  `tamano` CHAR(45) NOT NULL,
  PRIMARY KEY (`id_tamano`)
);

-- Insertar datos en tabla de tamaños
INSERT INTO `tbl_tamanos` (`id_tamano`, `tamano`) VALUES
(1, 'Individual'),
(2, 'Mediana'),
(3, 'Grande'),
(4, 'Super Grande');

-- Crear tabla de alérgenos
CREATE TABLE `tbl_alergenos` (
  `id_alergeno` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre_alergeno` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_alergeno`)
);

-- Insertar datos en tabla de alérgenos
INSERT INTO `tbl_alergenos` (`id_alergeno`, `nombre_alergeno`) VALUES
(1, 'Cacahuetes'),
(2, 'Frutos de cascara'),
(3, 'Soja'),
(4, 'Granos de sesamo'),
(5, 'Dioxido de azufre y sulfitos'),
(6, 'Gluten');

-- Crear tabla de categorías
CREATE TABLE `tbl_categorias` (
  `id_categoria` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre_categoria` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_categoria`)
);

-- Insertar datos en tabla de categorías
INSERT INTO `tbl_categorias` (`id_categoria`, `nombre_categoria`) VALUES
(1, 'Sin Gluten'),
(2, 'Salados'),
(3, 'Bolleria'),
(4, 'Rolls'),
(5, 'Pasteleria');

-- Crear tabla de productos
CREATE TABLE `tbl_productos` (
  `id_producto` INT(11) NOT NULL AUTO_INCREMENT,
  `codigo_producto` CHAR(45) NOT NULL,
  `nombre_producto` VARCHAR(45) NOT NULL,
  `disponibilidad_producto` CHAR(45) NOT NULL,
  `modalidad_producto` VARCHAR(450) NOT NULL,
  `estado_producto` CHAR(50) NOT NULL,
  `conservacion_producto` VARCHAR(45) NOT NULL,
  `precio_producto` DECIMAL(10,2) NOT NULL,
  `id_tamano` INT(11) NOT NULL,
  PRIMARY KEY (`id_producto`),
  FOREIGN KEY (`id_tamano`) REFERENCES `tbl_tamanos` (`id_tamano`)
);

-- Crear tabla de relación entre producto e ingrediente
CREATE TABLE `tbl_producto_ingrediente` (
  `id_producto` INT(11) NOT NULL,
  `id_ingrediente` INT(11) NOT NULL,
  FOREIGN KEY (`id_producto`) REFERENCES `tbl_productos` (`id_producto`),
  FOREIGN KEY (`id_ingrediente`) REFERENCES `tbl_ingredientes` (`id_ingrediente`)
);

-- Crear tabla de relación entre producto y alérgeno
CREATE TABLE `tbl_producto_alergeno` (
  `id_producto` INT(11) NOT NULL,
  `id_alergeno` INT(11) NOT NULL,
  FOREIGN KEY (`id_producto`) REFERENCES `tbl_productos` (`id_producto`),
  FOREIGN KEY (`id_alergeno`) REFERENCES `tbl_alergenos` (`id_alergeno`)
);

-- Crear tabla de relación entre producto y categoría
CREATE TABLE `tbl_producto_categoria` (
  `id_producto` INT(11) NOT NULL,
  `id_categoria` INT(11) NOT NULL,
  FOREIGN KEY (`id_producto`) REFERENCES `tbl_productos` (`id_producto`),
  FOREIGN KEY (`id_categoria`) REFERENCES `tbl_categorias` (`id_categoria`)
);


COMMIT;
