USE `bd_productos_sanetta`;

-- Insertar datos en tabla de ingredientes
INSERT INTO `tbl_ingredientes` (`id_ingrediente`, `nombre`) VALUES
(1, 'Agua del grifo'),
(2, 'Leche de soja'),
(3, 'Gelcremfred'),
(4, 'Cobertura negra 70%'),
(5, 'Sal'),
(6, 'Aceite girasol'),
(7, 'Cremoso de Chocolate'),
(8, 'Cobertura negra 55%'),
(9, 'Azúcar blanco'),
(10, 'Glucosa'),
(11, 'Cacao en polvo'),
(12, 'Pectina NH'),
(13, 'Baño de chocolate'),
(14, 'Harina de trigo floja'),
(15, 'Levadura química'),
(16, 'Proteina patata'),
(17, 'Azúcar moreno'),
(18, 'Nata'),
(19, 'Queso tofutti'),
(20, 'Disco 24 cm'),
(21, 'Caja 26 cm'),
(22, 'Margarina'),
(23, 'Coco rallado'),
(24, 'Remolacha cocida'),
(25, 'Glass'),
(26, 'Anacardos crudos'),
(27, 'Aceite de coco'),
(28, 'Colorante rojo en polvo'),
(29, 'Levadura fresca'),
(30, 'Harina media fuerza'),
(31, 'Canela molida'),
(32, 'Gotas chocolate'),
(33, 'Avellanas'),
(34, 'Banana'),
(35, 'Mix sin gluten'),
(36, 'Panela'),
(37, 'Nueces'),
(38, 'Manzana'),
(39, 'Cebolla morada'),
(40, 'Zumo limón'),
(41, 'Pasas'),
(42, 'Maizena'),
(43, 'Almidón tapioca'),
(44, 'Trigo sarraceno ECO'),
(45, 'Fécula patata'),
(46, 'Harina de arroz'),
(47, 'Corteza limón troceada'),
(48, 'Corteza naranja troceada'),
(49, 'Gelcremcalent'),
(50, 'Leche coco en polvo'),
(51, 'Pasta almendra cruda'),
(52, 'Puré pasión'),
(53, 'Inulina'),
(54, 'Vainilla pasta'),
(55, 'Lecitina de soja'),
(56, 'Vegan mousse'),
(57, 'Naturemul'),
(58, 'Agar-agar'),
(59, 'Pure frutos rojos'),
(60, 'Frambuesa congelada'),
(61, 'Xantana'),
(62, 'Vinagre de manzana'),
(63, 'Harina de almendra'),
(64, 'Bicarbonato'),
(65, 'Manteca de cacao'),
(66, 'Amaretto'),
(67, 'Frutos rojos congelados'),
(68, 'Jengibre en polvo'),
(69, 'Nuez moscada en grano'),
(70, 'Puré frambuesa'),
(71, 'Colorante rojo en pasta'),
(72, 'Copos de avena sin gluten'),
(73, 'Almendra en bastoncitos'),
(74, 'Sojawhip'),
(75, 'Yogur soja'),
(76, 'Pistacho pelado'),
(77, 'Queso mozarella rallada'),
(78, 'Pimienta negra'),
(79, 'Orégano seco'),
(80, 'Pimentón picante'),
(81, 'Pimentón dulce'),
(82, 'Ajo en polvo'),
(83, 'Cúrcuma en polvo'),
(84, 'Cajita individual roll'),
(85, 'Nutela'),
(86, 'Leche coco en la lata'),
(87, 'Dulce de leche'),
(88, 'Crema de limón'),
(89, 'Merengue italiano'),
(90, 'Bizcocho cacao grande (p)'),
(91, 'Caja 23 cm'),
(92, 'Disco 21 cm'),
(93, 'Roll canela (p)'),
(94, 'Discos 30 cm'),
(95, 'Caja 32 cm'),
(96, 'Bizcocho tiramisu'),
(97, 'Salsa f.r. tiramisu'),
(98, 'Spray terciopelo rojo'),
(99, 'Crema tiramisu'),
(100, 'Cartoncito 8 cm'),
(101, 'Café expreso'),
(102, 'Café tiramisú'),
(103, 'Zanahoria'),
(104, 'Bizcocho carrot grande (p)'),
(105, 'Bizcocho cacao grande sg (p)'),
(106, 'Bizcocho carrot grande sg (p)'),
(107, 'Mermelada frambuesa'),
(108, 'Bizcocho pink velvet grande'),
(109, 'Bizcocho pink velvet grande sg'),
(110, 'Cookies doble chocolate'),
(111, 'Pasta brisa sin azúcar'),
(112, 'Almidón patata'),
(113, 'Dátiles pasta'),
(114, 'Crumble'),
(115, 'Glass antihumedad'),
(116, 'Pasta sable de almendra'),
(117, 'Soplete'),
(118, 'Chocolate blanco casero'),
(119, 'Praline avellana'),
(120, 'Plancha cacao sg'),
(121, 'Mousse chocolate 70%'),
(122, 'Mermelada frutos rojos'),
(123, 'Frutos rojos frescos'),
(124, 'Gel frío'),
(125, 'Manzana roll'),
(126, 'Carton base 20cm'),
(127, 'Carton base 22 cm'),
(128, 'Vasito compostable'),
(129, 'Ganache macaron choco sg (p)'),
(130, 'Base macaron sg (p)'),
(131, 'Flor de sal'),
(132, 'Harina trigo integral'),
(133, 'Aceite de oliva'),
(134, 'Masa quiche'),
(135, 'Levadura nutricional'),
(136, 'Cebolla blanca'),
(137, 'Papelinas nº8'),
(138, 'Tomate frito'),
(139, 'Aceituna negra'),
(140, 'Cajas catering marron'),
(141, 'Cajas catering blanca'),
(142, 'Papel de horno'),
(143, 'Tomate seco'),
(144, 'Pimiento rojo'),
(145, 'Pimiento verde'),
(146, 'Caja plumcake'),
(147, 'Base rectangular'),
(148, 'Cebolla caramelizada'),
(149, 'Griottines'),
(150, 'Comino en polvo'),
(151, 'Sobrasada'),
(152, 'Ralladura limón'),
(153, 'Crema de almendras'),
(154, 'Nueces pecanas'),
(155, 'Bizcocho german cake (p)'),
(156, 'Crema german cake (p)'),
(157, 'Caja alta de 15 cm alto grande'),
(158, 'Bizcocho almendra sin gluten (p)'),
(159, 'Margarina casera'),
(160, 'Sirope de Agave'),
(161, 'Goma garrofín'),
(162, 'Ganache opera'),
(163, 'Glaseado opera'),
(164, 'Crema cafe opera'),
(165, 'Polvo dorado'),
(166, 'Cebolla cortada congelada'),
(167, 'Cacahuetes'),
(168, 'Calabaza'),
(169, 'Mermelada calabaza'),
(170, 'Brisa de cacao'),
(171, 'Anis del mono'),
(172, 'Pistachos'),
(173, 'Pasta pura pistacho'),
(174, 'Mazapan'),
(175, 'Pipas calabaza'),
(176, 'Eko'),
(177, 'Piñon castellano'),
(178, 'Colorante negro'),
(179, 'Garrapiñadas de calabaza'),
(180, 'Ganache pistacho'),
(181, 'Praline avellana bon llevat'),
(182, 'Harina de trigo fuerza'),
(183, 'Harina de garbanzo'),
(184, 'Cabello de angel'),
(185, 'Café Soluble Classic'),
(186, 'Chocolate blanco'),
(187, 'Naranja fresca'),
(188, 'Baño almendra tronco vainilla'),
(189, 'Crumble almendra'),
(190, 'Bizcocho naranja sin gluten'),
(191, 'Confitura maracuya'),
(192, 'Mousse vainilla'),
(193, 'Frambuesa fresca'),
(194, 'Agua de azahar'),
(195, 'Roscones reyes'),
(196, 'Cajas roscon 26x26'),
(197, 'Cajas troncos'),
(198, 'Habas reyes'),
(199, 'Rey porcelana'),
(200, 'Corona reyes prince'),
(201, 'Crema pastelera'),
(202, 'Albahaca fresca'),
(203, 'Cebolla blanca grande'),
(204, 'Arandanos congelados'),
(205, 'Eritritol'),
(206, 'Sésamo tostado'),
(207, 'Anis en grano'),
(208, 'Cajitas san valentin'),
(209, 'Pipas girasol'),
(210, 'Piña fresca'),
(211, 'Menta fresca'),
(212, 'Maracuyá fresco'),
(213, 'Mermelada maracuyá'),
(214, 'Mango fresco'),
(215, 'Capsulas metal trufa'),
(216, 'Brownie (p)'),
(217, 'Masa quiche'),
(218, 'Champiñones'),
(219, 'Calabacin'),
(220, 'Espinacas'),
(221, 'Puerro'),
(222, 'Mousse genércia'),
(223, 'Bizcocho calabacin grande sin gluten'),
(224, 'Peras'),
(225, 'Romero'),
(226, 'Physalis'),
(227, 'Cookies doble chocolate sin gluten'),
(228, 'Cebollino'),
(229, 'Patata'),
(230, 'Pmiento rojo'),
(231, 'Berenjena'),
(232, 'Alcaparras'),
(233, 'Soja texturizada'),
(234, 'Vino blanco'),
(235, 'Chorizo heura'),
(236, 'Farça chorizo, patata y queso'),
(237, 'Farça verduritas con soja text.'),
(238, 'Farça champiñon'),
(239, 'Pollo heura'),
(240, 'Salsa pesto');

-- Insertar datos en tabla de tamaños
INSERT INTO `tbl_tamanos` (`id_tamano`, `tamano`) VALUES
(1, 'Individual'),
(2, 'Mediana'),
(3, 'Grande'),
(4, 'Super Grande');

-- Insertar datos en tabla de alérgenos
INSERT INTO `tbl_alergenos` (`id_alergeno`, `nombre_alergeno`) VALUES
(1, 'Cacahuetes'),
(2, 'Frutos de cascara'),
(3, 'Soja'),
(4, 'Granos de sesamo'),
(5, 'Dioxido de azufre y sulfitos'),
(6, 'Gluten');

-- Insertar datos en tabla de categorías
INSERT INTO `tbl_categorias` (`id_categoria`, `nombre_categoria`) VALUES
(1, 'Sin Gluten'),
(2, 'Salados'),
(3, 'Bolleria'),
(4, 'Rolls'),
(5, 'Pasteleria');

-- Insertar datos en la tabla de productos
INSERT INTO tbl_productos (codigo_producto, nombre_producto, unidades, gluten, azucar, id_tamano, conservacion_producto) VALUES
('BBr-01', 'Pastelito Brownie', 1, 'Sin', 'Con', 1, 'frío'),
('BBr-02', 'Pastelito Brownie Cremoso', 1, 'Sin', 'Con', 1, 'frío'),
('BBr-03', 'Caja Mini Brownie (35 und.)', 1, 'Sin', 'Con', 1, 'frío'),
('BCo-01', 'Cookie Avellana y Naranja', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BCo-02', 'Cookie Chocolate Blanco y Cacahuetes', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BCo-03', 'Cookie Chocolate y Nueces', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BCo-04', 'Cookie Doble Chocolate', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BCo-05', 'Cookie Pistacho y Frambuesa', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BCo-06', 'Cookie Romero y Limón', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BCo-07', 'Cookie Avellana y Naranja SG', 1, 'Sin', 'Con', 1, 'temperatura ambiente'),
('BCo-08', 'Cookie Chocolate Blanco y Cacahuetes SG', 1, 'Sin', 'Con', 1, 'temperatura ambiente'),
('BCo-09', 'Cookie Chocolate y Nueces SG', 1, 'Sin', 'Con', 1, 'temperatura ambiente'),
('BCo-10', 'Cookie Doble Chocolate SG', 1, 'Sin', 'Con', 1, 'temperatura ambiente'),
('BCo-11', 'Cookie Romero y Limón SG', 1, 'Sin', 'Con', 1, 'temperatura ambiente'),
('BCu-01', 'Cup Cakes', 1, 'Sin', 'Con', 1, 'temperatura ambiente'),
('BEn-01', 'Ensaimada Cabello de Angel', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BEn-02', 'Ensaimada Normal', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BEn-03', 'Ensaimada Nutella', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BEn-04', 'Ensaimada Rellena con Nata', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BEn-05', 'Ensaimada Rellena Dulce de Leche', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BEn-06', 'Ensaimada Sobrasada', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BMc-01', 'Macarrons', 1, 'Sin', 'Con', 1, 'frío'),
('BMc-02', 'Macarrons pistacho', 1, 'Sin', 'Con', 1, 'frío'),
('BMc-03', 'Macarrons Cassís Y Chocolate', 1, 'Sin', 'Con', 1, 'frío'),
('BMc-04', 'Macarrons Chocolate', 1, 'Sin', 'Con', 1, 'frío'),
('BMc-05', 'Macarrons Crema de Limón', 1, 'Sin', 'Con', 1, 'frío'),
('BMc-06', 'Macarrons Frambuesa', 1, 'Sin', 'Con', 1, 'frío'),
('BMg-01', 'Magdalenas Francesas con Chocolate Blanco', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BMg-02', 'Magdalenas Arándanos', 1, 'Sin', 'Con', 1, 'temperatura ambiente'),
('BMg-03', 'Magdalenas vainilla y chocolate', 1, 'Sin', 'Con', 1, 'temperatura ambiente'),
('BMg-04', 'Magdalenas Francesas con Nueces', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BMg-05', 'Magdalenas doble Chocolate', 1, 'Sin', 'Con', 1, 'temperatura ambiente'),
('BMg-06', 'Magdalenas Vainilla', 1, 'Sin', 'Con', 1, 'temperatura ambiente'),
('BMg-07', 'Magdalenas Francesas con Chocolate Blanco SG', 1, 'Sin', 'Con', 1, 'temperatura ambiente'),
('BMg-08', 'Magdalenas Francesas con Nueces SG', 1, 'Sin', 'Con', 1, 'temperatura ambiente'),
('Pmo-02', 'Pastelito Mousse Choco y Frambuesa', 1, 'Sin', 'Con', 1, 'frío'),
('BPn-01', 'Panellets de Pistacho', 1, 'Sin', 'Con', 1, 'temperatura ambiente'),
('BPn-02', 'Panellets de Café de Cereales', 1, 'Sin', 'Con', 1, 'temperatura ambiente'),
('BPn-03', 'Panellets de Piñon', 1, 'Sin', 'Con', 1, 'temperatura ambiente'),
('BPn-04', 'Panellets de Almendra', 1, 'Sin', 'Con', 1, 'temperatura ambiente'),
('BPn-05', 'Panellets de Coco', 1, 'Sin', 'Con', 1, 'temperatura ambiente'),
('BPn-06', 'Panellets de Choco-Coco', 1, 'Sin', 'Con', 1, 'temperatura ambiente'),
('BPt-01', 'Pastas De Te Variadas C/A /0.5Kg', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BPt-02', 'Pastas De Te Variadas C/A /1kg', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BPt-03', 'Pastas De Te S/A /0.5Kg', 1, 'Con', 'Sin', 1, 'temperatura ambiente'),
('BPt-04', 'Pastas De Te S/A /1kg', 1, 'Con', 'Sin', 1, 'temperatura ambiente'),
('BTr-01', 'Trenza Chocolate', 1, 'Sin', 'Con', 1, 'temperatura ambiente'),
('BTr-02', 'Trenza Nata', 1, 'Sin', 'Con', 1, 'temperatura ambiente'),
('BTr-03', 'Trenza Crema', 1, 'Sin', 'Con', 1, 'temperatura ambiente'),
('BTr-04', 'Trenza Trufa', 1, 'Sin', 'Con', 1, 'temperatura ambiente'),
('BTr-05', 'Trenza Chocolate blanco', 1, 'Sin', 'Con', 1, 'temperatura ambiente'),
('BTx-01', 'Txurro Normal', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BTx-02', 'Txurro Chocolate', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BTx-03', 'Txurro Chocolate Blanco', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BTx-04', 'Txurro Avellana', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BTx-05', 'Txurro Crema', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BTx-06', 'Txurro Fresa', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BTx-07', 'Txurro Chocolate con Naranja', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BTx-08', 'Txurro Chocolate con Menta', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BTx-09', 'Txurro Trufa', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BTx-10', 'Txurro Vainilla', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BAm-01', 'Americano', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BAm-02', 'Donuts Glasse', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BAm-03', 'Donuts Glasse Chocolate', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BAm-04', 'Donuts Glasse Frambuesa', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BAm-05', 'Donuts Glasse Fresa', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BAm-06', 'Donuts Glasse Naranja', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BAm-07', 'Donuts Glasse Menta', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BAm-08', 'Donuts Glasse Platano', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BAm-09', 'Donuts Glasse Zanahoria', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BAm-10', 'Donuts Glasse Cafe', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BAm-11', 'Donuts Glasse Limon', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BAm-12', 'Donuts Glasse Te', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BAm-13', 'Donuts Glasse Mango', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BAm-14', 'Donuts Glasse Manzana', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BAm-15', 'Donuts Glasse Vainilla', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BAm-16', 'Donuts Glasse chocolate Blanco', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BAm-17', 'Donuts Glasse Chocolate con Leche', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BAm-18', 'Donuts Glasse Nata', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BAm-19', 'Donuts Glasse Dulce de Leche', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BAm-20', 'Donuts Glasse Chocolate Blanco y Negro', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BAm-21', 'Donuts Glasse Chocolate con Cereales', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BAm-22', 'Donuts Glasse Chocolate con Almendras', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BAm-23', 'Donuts Glasse Chocolate con Nueces', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BAm-24', 'Donuts Glasse Chocolate con Avellanas', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BAm-25', 'Donuts Glasse Chocolate con Pistachos', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BAm-26', 'Donuts Glasse Chocolate con Pera', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BAm-27', 'Donuts Glasse Chocolate con Platano', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BAm-28', 'Donuts Glasse Chocolate con Zanahoria', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BAm-29', 'Donuts Glasse Chocolate con Calabaza', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BAm-30', 'Donuts Glasse Chocolate con Coco', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BAm-31', 'Donuts Glasse Chocolate con Frambuesa', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BAm-32', 'Donuts Glasse Chocolate con Fresa', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BAm-33', 'Donuts Glasse Chocolate con Guayaba', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BAm-34', 'Donuts Glasse Chocolate con Kiwi', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BAm-35', 'Donuts Glasse Chocolate con Mango', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BAm-36', 'Donuts Glasse Chocolate con Maracuya', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BAm-37', 'Donuts Glasse Chocolate con Melocotón', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BAm-38', 'Donuts Glasse Chocolate con Naranja', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BAm-39', 'Donuts Glasse Chocolate con Papaya', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BAm-40', 'Donuts Glasse Chocolate con Piña', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BAm-41', 'Donuts Glasse Chocolate con Platano', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BAm-42', 'Donuts Glasse Chocolate con Sandia', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BAm-43', 'Donuts Glasse Chocolate con Uva', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BAm-44', 'Donuts Glasse Chocolate con Zanahoria', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BAm-45', 'Donuts Glasse Chocolate con Pera', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BAm-46', 'Donuts Glasse Chocolate con Calabaza', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BAm-47', 'Donuts Glasse Chocolate con Caramelo', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BAm-48', 'Donuts Glasse Chocolate con Almendras', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BAm-49', 'Donuts Glasse Chocolate con Avellanas', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BAm-50', 'Donuts Glasse Chocolate con Pistachos', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BAm-51', 'Donuts Glasse Chocolate con Avellanas y Pistachos', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BAm-52', 'Donuts Glasse Chocolate con Avellanas y Coco', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BAm-53', 'Donuts Glasse Chocolate con Avellanas y Fresa', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BAm-54', 'Donuts Glasse Chocolate con Avellanas y Frambuesa', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BAm-55', 'Donuts Glasse Chocolate con Avellanas y Guayaba', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BAm-56', 'Donuts Glasse Chocolate con Avellanas y Kiwi', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BAm-57', 'Donuts Glasse Chocolate con Avellanas y Mango', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BAm-58', 'Donuts Glasse Chocolate con Avellanas y Maracuya', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BAm-59', 'Donuts Glasse Chocolate con Avellanas y Melocotón', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BAm-60', 'Donuts Glasse Chocolate con Avellanas y Naranja', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BAm-61', 'Donuts Glasse Chocolate con Avellanas y Papaya', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BAm-62', 'Donuts Glasse Chocolate con Avellanas y Piña', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BAm-63', 'Donuts Glasse Chocolate con Avellanas y Platano', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BAm-64', 'Donuts Glasse Chocolate con Avellanas y Sandia', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BAm-65', 'Donuts Glasse Chocolate con Avellanas y Uva', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BAm-66', 'Donuts Glasse Chocolate con Avellanas y Zanahoria', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BAm-67', 'Donuts Glasse Chocolate con Avellanas y Pera', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BAm-68', 'Donuts Glasse Chocolate con Avellanas y Calabaza', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BAm-69', 'Donuts Glasse Chocolate con Avellanas y Caramelo', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BAm-70', 'Donuts Glasse Chocolate con Avellanas y Nueces', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BAm-71', 'Donuts Glasse Chocolate con Avellanas y Coco', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BAm-72', 'Donuts Glasse Chocolate con Avellanas y Fresa', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BAm-73', 'Donuts Glasse Chocolate con Avellanas y Frambuesa', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BAm-74', 'Donuts Glasse Chocolate con Avellanas y Guayaba', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BAm-75', 'Donuts Glasse Chocolate con Avellanas y Kiwi', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BAm-76', 'Donuts Glasse Chocolate con Avellanas y Mango', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BAm-77', 'Donuts Glasse Chocolate con Avellanas y Maracuya', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BAm-78', 'Donuts Glasse Chocolate con Avellanas y Melocotón', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BAm-79', 'Donuts Glasse Chocolate con Avellanas y Naranja', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BAm-80', 'Donuts Glasse Chocolate con Avellanas y Papaya', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BAm-81', 'Donuts Glasse Chocolate con Avellanas y Piña', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BAm-82', 'Donuts Glasse Chocolate con Avellanas y Platano', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BAm-83', 'Donuts Glasse Chocolate con Avellanas y Sandia', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BAm-84', 'Donuts Glasse Chocolate con Avellanas y Uva', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BAm-85', 'Donuts Glasse Chocolate con Avellanas y Zanahoria', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BAm-86', 'Donuts Glasse Chocolate con Avellanas y Pera', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BAm-87', 'Donuts Glasse Chocolate con Avellanas y Calabaza', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BAm-88', 'Donuts Glasse Chocolate con Avellanas y Caramelo', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BAm-89', 'Donuts Glasse Chocolate con Nueces', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BAm-90', 'Donuts Glasse Chocolate con Coco', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BAm-91', 'Donuts Glasse Chocolate con Fresa', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BAm-92', 'Donuts Glasse Chocolate con Frambuesa', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BAm-93', 'Donuts Glasse Chocolate con Guayaba', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BAm-94', 'Donuts Glasse Chocolate con Kiwi', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BAm-95', 'Donuts Glasse Chocolate con Mango', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BAm-96', 'Donuts Glasse Chocolate con Maracuya', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BAm-97', 'Donuts Glasse Chocolate con Melocotón', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BAm-98', 'Donuts Glasse Chocolate con Naranja', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BAm-99', 'Donuts Glasse Chocolate con Papaya', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BAm-100', 'Donuts Glasse Chocolate con Piña', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BAm-101', 'Donuts Glasse Chocolate con Platano', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BAm-102', 'Donuts Glasse Chocolate con Sandia', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BAm-103', 'Donuts Glasse Chocolate con Uva', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BAm-104', 'Donuts Glasse Chocolate con Zanahoria', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BAm-105', 'Donuts Glasse Chocolate con Pera', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BAm-106', 'Donuts Glasse Chocolate con Calabaza', 1, 'Con', 'Con', 1, 'temperatura ambiente'),
('BAm-107', 'Donuts Glasse Chocolate con Caramelo', 1, 'Con', 'Con', 1, 'temperatura ambiente');
